@host = http://localhost:8080
# config: https://github.com/thangchung/coffeeshop-on-nomad/wiki/Know-how
# @host = http://nomadvn.eastus.cloudapp.azure.com

### Get Todos
# dotnet user-jwts create --claim "myCustomClaim=green"
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InJvb3QiLCJzdWIiOiJyb290IiwianRpIjoiYzRmOThiNzkiLCJteUN1c3RvbUNsYWltIjoiZ3JlZW4iLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjgwODAiLCJuYmYiOjE2Njg2MDE5MzUsImV4cCI6MTY3NjU1MDczNSwiaWF0IjoxNjY4NjAxOTM2LCJpc3MiOiJkb3RuZXQtdXNlci1qd3RzIn0.eNHf6DKp5zL9UIKHWhUhh5f4ZaQNDIyP3BI2DDA0-wc

###
GET {{host}}/product-api/v1/api/item-types HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

###
GET {{host}}/product-api/v1/api/items-by-types/1,2,3 HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

###
POST {{host}}/counter-api/v1/api/orders HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
  "commandType": 0,
  "orderSource": 0,
  "location": 0,
  "loyaltyMemberId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "baristaItems": [
    {
      "itemType": {{$randomInt 0 5}}
    },
    {
      "itemType": {{$randomInt 0 5}}
    }
  ],
  "kitchenItems": [
    {
      "itemType": {{$randomInt 6 9}}
    }
  ],
  "timestamp": "2022-07-04T11:38:00.210Z"
}

###
GET {{host}}/counter-api/v1/api/fulfillment-orders HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json