@productHost = http://localhost:5001
@counterHost = http://localhost:5002
@host = http://localhost:5000

###
GET {{productHost}}/v1/item/ping HTTP/1.1
content-type: application/json

###
GET {{productHost}}/v1/item-types HTTP/1.1
content-type: application/json

###
GET {{productHost}}/v1/items-by-types/1,2,3 HTTP/1.1
content-type: application/json

###
POST {{host}}/apis/counter/v1/api/orders HTTP/1.1
content-type: application/json

{
  "commandType": 0,
  "orderSource": 0,
  "location": 0,
  "loyaltyMemberId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "baristaItems": [
    {
      "itemType": {{$randomInt 0 5}}
    }
  ],
  "kitchenItems": [
    {
      "itemType": {{$randomInt 6 9}}
    }
  ],
  "timestamp": "2022-07-04T11:38:00.210Z"
}

###
GET {{host}}/apis/counter/v1/api/fulfillment-orders HTTP/1.1
content-type: application/json