# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Start from this base box
  config.vm.box = "hashicorp/bionic64"

  # Increase memory for Virtualbox
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "10240"
  end

  # Copy Nomad job files to host
  config.vm.provision "file", source: "jobs", destination: "jobs"
  config.vm.synced_folder "jobs/", "/jobs"

  # Run the bootstrap script
  config.vm.provision "shell", path: "start.sh"

  # Expose the nomad api and ui to the host
  config.vm.network "forwarded_port", guest: 4646, host: 4646, auto_correct: true, host_ip: "127.0.0.1"

  # Expose the consul api and ui to the host
  config.vm.network "forwarded_port", guest: 8500, host: 8500, auto_correct: true, host_ip: "127.0.0.1"

  # Expose the vault api and ui to the host
  config.vm.network "forwarded_port", guest: 8200, host: 8200, auto_correct: true, host_ip: "127.0.0.1"

  # Expose the traefik service ports to the host
  config.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true, host_ip: "127.0.0.1" # Traefik HTTP
  config.vm.network "forwarded_port", guest: 443, host: 8443, auto_correct: true, host_ip: "127.0.0.1" # Traefik HTTPS
  config.vm.network "forwarded_port", guest: 8080, host: 8888, auto_correct: true, host_ip: "127.0.0.1" # Traefik /dashboard

  config.vm.network "forwarded_port", guest: 5432, host: 5432, auto_correct: true, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 15672, host: 15672, auto_correct: true, host_ip: "127.0.0.1"
end
